include = [
  "examples/*.toml",
]

# Level 0
[[services]]
name = "alpha_core"
executable = "bash"
enabled = '{{ gt ((env "TEST_JSON" | b64dec | fromJSON).field |toInt) 20 }}'
args = [
  "-c",
  "echo Alpha Core initializing",
]
inherit_env = true
type = "normal"
process_count = 3

# Level 1
[[services]]
name = "bravo_agent"
executable = "bash"
requires = [
  "alpha_core",
]
enabled = '{{ gt ((env "TEST_JSON" | b64dec | fromJSON).field |toInt) 20 }}'
args = [
  "-c",
  "date && echo Bravo Agent running",
]
inherit_env = true
type = "one-shot"

[[services]]
name = "charlie_listener"
executable = "bash"
requires = [
  "alpha_core",
]
enabled = '{{ gt ((env "TEST_JSON" | b64dec | fromJSON).field |toInt) 20 }}'
args = [
  "-c",
  "echo Listening for events...; sleep 2",
]
inherit_env = true
type = "normal"
stdout = "file,./charlie.log"

# Level 2
[[services]]
name = "delta_worker"
executable = "bash"
requires = [
  "bravo_agent",
  "charlie_listener",
]
enabled = '{{ gt ((env "TEST_JSON" | b64dec | fromJSON).field |toInt) 20 }}'
args = [
  "-c",
  "for i in {1..5}; do echo Delta working...; sleep 1; done",
]
inherit_env = true
type = "normal"
process_count = 2

[[services]]
name = "echo_collector"
executable = "bash"

lazy = true
requires = [
  "charlie_listener",
]
enabled = '{{ gt ((env "TEST_JSON" | b64dec | fromJSON).field |toInt) 20 }}'
args = [
  "-c",
  "echo Collecting data into ./collector.log",
]
inherit_env = true
type = "one-shot"
stdout = "file,./collector.log"

# Level 3
[[services]]
name = "foxtrot_reporter"
executable = "bash"
requires = [
  "delta_worker",
  "echo_collector",
]
lazy = "$DISABLED"
enabled = '{{ gt ((env "TEST_JSON" | b64dec | fromJSON).field |toInt) 20 }}'
args = [
  "-c",
  "echo Generating final report... && date",
]
inherit_env = true
type = "one-shot"
stdout = "file,./final_report.log"

[[services]]
name = "golf_monitor"
executable = "bash"
requires = [
  "delta_worker",
]
enabled = '{{ gt ((env "TEST_JSON" | b64dec | fromJSON).field |toInt) 20 }}'
args = [
  "-c",
  "echo Monitoring service health...; sleep 3",
]
inherit_env = true
type = "normal"
process_count = 1
