include = [
  "examples/*.toml",
]

[[services]]
name = "simple"
executable = "bash"
enabled = '{{ gt ((env "TEST_JSON" | b64dec | fromJSON).field |toInt) 20 }}'
args = [
  "-c",
  "echo oneshot",
]
inherit_env = true
type = "one-shot"
process_count = 15

[[services]]
name = "simple2"
executable = "bash"
enabled = '{{ gt ((env "TEST_JSON" | b64dec | fromJSON).field |toInt) 20 }}'
args = [
  "-c",
  "date; exit 1",
]
inherit_env = true
type = "normal"
stdout = "file,./test.log"
# restart.count = 15
