include = ["examples/*.toml"]

[[services]]
name = "simple"
executable = "bash"
enabled = '{{ gt ((env "TEST_JSON" | b64dec | fromJSON).field |toInt) 20 }}'
args = ["-c", "echo oneshot"]
env_passtru = true
env_file = "test.env"
type = "one-shot"

[[services]]
name = "simple2"
executable = "bash"
enabled = '{{ gt ((env "TEST_JSON" | b64dec | fromJSON).field |toInt) 20 }}'
args = ["-c", "echo 'in looooooop' >&2; exit 1"]
env_passtru = true
env_file = "test.env"
type = "normal"

# restart.count = 15
