include = ["examples/*.toml"]
[[services]]
name = "test"
executable = "sh"
args = ["-c", "echo 'Hello from the init sh!'"]
type = "multi-shot"

dependents = ["simple"]

[[services]]
name = "setup"
executable = "sh"
args = ["-c", "echo 'setup!'"]
type = "multi-shot"

dependents = ["simple"]
